<Start>
  GridLayout:
    cols: 1
    GridLayout:
      cols: 4
      height:
      Label:
        text: "Module number 1"
      GridLayout:
        rows:2
        height:
        orientation: "tb-lr"
        Label:
          text: "Temperature"
        Label:
          text: "Thermistor ID"
      GridLayout:
        rows:2
        height:
        orientation: "tb-lr"
        Label:
          text: "Temperature"
        Label:
          text: "Thermistor ID"
    GridLayout:
      cols: 4
      height:
      Label:
        text: "Module number 1"
      GridLayout:
        rows:2
        height:
        orientation: "tb-lr"
        Label:
          text: "Temperature"
        Label:
          text: "Thermistor ID"
      GridLayout:
        rows:2
        height:
        orientation: "tb-lr"
        Label:
          text: "Temperature"
        Label:
          text: "Thermistor ID"